---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    securityContext:
      readOnlyRootFileSystem: true
    volumeMounts:
    - mountpath: /var/log/nginx
      name: nginx-logs
  volumes:
  - name: nginx-logs
    emptyDir: {}
---